version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: finance-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - finance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d wallet_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: finance-messenger
    restart: always
    ports:
      - "5672:5672"   # Mensajeria
      - "15672:15672" # Painel de Gestão
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - finance-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  finance-network:
    driver: bridge